# Generated by Django 2.1.7 on 2023-08-03 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230803_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 3, 17, 14, 35, 738365)),
        ),
    ]
